"use client";

import { Metadata } from "next";
import Link from "next/link";
import { useRouter } from "next/navigation";

// * 상수 선언부 */
import { prefix } from "./config/config";

import AppHeader from "./components/header";
import AppFooter from "./components/footer";

import { Button } from "@mui/material";
import LoyaltyIcon from "@mui/icons-material/Loyalty";
import CardGiftcardIcon from "@mui/icons-material/CardGiftcard";
// export const metadata: Metadata = {
//   title: "main | Tarot For Love",
//   description: "Generated by create next app",
// };

export default function Home() {
  const router = useRouter();
  return (
    <>
      <AppHeader />
      <ul className="gnb flex-center">
        <li>오늘의 질문</li>
        <li>오늘의 타로</li>
        <li>오늘의 데이트 코스</li>
      </ul>
      <main className="flex min-h-screen flex-col items-center flex-start p-24">
        <section className="day-counter">
          <h2>처음 만난 날 200일째</h2>
          <div className="couple-name">영희 ♡ 철수</div>
        </section>

        <section className="today-question">
          <h2>
            <LoyaltyIcon />
            오늘의 질문
          </h2>
          <div>
            <Link href="/question">
              비오는 날은 주로 뭘 하며 시간을 보내나요?
            </Link>
          </div>
        </section>

        <section className="today-tarot">
          <h2>
            <CardGiftcardIcon />
            오늘의 타로
          </h2>
          <div>
            <Button
              variant="contained"
              // endIcon={<PersonAddIcon />}
              onClick={() => router.push("/tarot/")}
            >
              지금 바로 카드 확인
            </Button>
          </div>
        </section>

        <section className="today-place">
          <h2>오늘의 데이트 코스</h2>
          <div>
            <ul>
              <li>
                <a href="#">
                  <img src="" alt="" />
                  <dl>
                    <dt></dt>
                    <dd></dd>
                  </dl>
                </a>
              </li>
              <li>
                <a href="#">
                  <img src="" alt="" />
                  <dl>
                    <dt></dt>
                    <dd></dd>
                  </dl>
                </a>
              </li>
            </ul>
          </div>
        </section>
      </main>
      <AppFooter />
      <style jsx>{`
        h2 {
          padding: 0;
          display: flex;
          align-items: center;
          justify-content: center;
        }
        h2::after {
          display: none;
        }

        section > div {
          display: flex;
          align-items: center;
          justify-content: center;
        }

        .day-counter {
          width: 100%;
          height: 33.3333%;
          position: relative;
        }
        .day-counter::after {
          display: inline-block;
          content: "";
          width: 100%;
          height: 100%;
          position: absolute;
          left: 0;
          top: 0;
          background: url("/images/couple_main_bg.jpg") no-repeat center;
          opacity: 0.5;
          z-index: -1;
        }
        .day-counter h2 {
          width: 100%;
          padding: 10px 0;
          text-align: center;
        }
        .day-counter .couple-name {
          font-size: 16px;
          font-weight: 600;
          text-align: center;
          margin: 0 auto;
        }

        .today-question {
          width: 100%;
          height: 25%;
        }

        .today-tarot {
          width: 100%;
          background: blue;
        }

        .today-tarot button {
          width: 300px;
        }
      `}</style>
      ;
    </>
  );
}
